
services:

  flask:
    build: ./flask
    container_name: flask
    restart: always
    depends_on:
      - redis
    environment:
      - FLASK_ENV=development
      - APP_NAME=HPCadmin
    volumes:
      - ./flask:/app
      - ../patching/:/data/patching
      - ../inventory/:/data/inventory
      #- /mnt/svm-chem/grid/univa:/mnt/svm-chem/grid/univa:ro
    expose:
      - 8080
    #Real host and domainname if ssl certs used  
    #hostname: gbjhccx00
    #domainname: region.company.org

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      #- "443:443"
    #volumes:
      #- ./certs/:/etc/nginx/ssl:ro

  redis:
    image: redis

  worker:
    build: ./flask
    container_name: worker
    restart: always 
    command: "celery -A app.HPCapps.tasks.celery worker --loglevel=DEBUG"
    user: nobody
    links:
        - redis
    volumes:
        - ./flask/:/app:ro
        - ../patching/:/data/patching
        - ../inventory/:/data/inventory

  #celery-beat:
   # build: ./flask
   # command: celery -A proj beat -l info
   # volumes:
     # - ./flask/:/app
    #depends_on:
      #- redis
      
  monitor:
    build:
      context: ./flask
      dockerfile: Dockerfile
    ports:
     - "5555:5555"
    entrypoint: flower
    command: "flower -A app.HPCapps.tasks.celery --port=5555 --broker=redis://redis:6379"
    depends_on:
      - redis
    volumes: ['./flask:/app:ro']

volumes:
    app: {}

